export const orderData = [
	{
		id: "1",
		naam: "Marien Fieret",
		tel: "0618844511",
		datum: "01 juni",
		pickUpTime: "11:30",
		bestelling: [
			{
				product: "Kabeljauw",
				hoeveelheid: "200gram",
				delen: 1,
				opties: ["met marinade", "in wokstukken gesneden"],
				prijs: 2399,
			},
			{
				product: "Zalm",
				hoeveelheid: "200gram",
				delen: 1,
				opties: ["met marinade", "in wokstukken gesneden"],
				prijs: 2399,
			},
			{
				product: "Tongschar",
				hoeveelheid: "200gram",
				delen: 1,
				opties: ["met marinade", "in wokstukken gesneden"],
				prijs: 2399,
			},
		],
		inpakStatus: "ready",
		aangenomen: "Jeanita",
		ingepakt: "Brenda",
	},
	{
		id: "2",
		naam: "Marien Fieret",
		tel: "0618844511",
		datum: "01 juni",
		pickUpTime: "11:30",
		bestelling: [
			{
				product: "Kabeljauw",
				hoeveelheid: "200gram",
				delen: 1,
				opties: ["met marinade", "in wokstukken gesneden"],
				prijs: 2399,
			},
			{
				product: "Zalm",
				hoeveelheid: "200gram",
				delen: 1,
				opties: ["met marinade", "in wokstukken gesneden"],
				prijs: 2399,
			},
			{
				product: "Tongschar",
				hoeveelheid: "200gram",
				delen: 1,
				opties: ["met marinade", "in wokstukken gesneden"],
				prijs: 2399,
			},
		],
		inpakStatus: "ready",
		aangenomen: "Jeanita",
		ingepakt: "Brenda",
	},
	{
		id: "3",
		naam: "Marien Fieret",
		tel: "0618844511",
		datum: "01 juni",
		pickUpTime: "11:30",
		bestelling: [
			{
				product: "Kabeljauw",
				hoeveelheid: "200gram",
				delen: 1,
				opties: ["met marinade", "in wokstukken gesneden"],
				prijs: 2399,
			},
			{
				product: "Zalm",
				hoeveelheid: "200gram",
				delen: 1,
				opties: ["met marinade", "in wokstukken gesneden"],
				prijs: 2399,
			},
			{
				product: "Tongschar",
				hoeveelheid: "200gram",
				delen: 1,
				opties: ["met marinade", "in wokstukken gesneden"],
				prijs: 2399,
			},
		],
		inpakStatus: "ready",
		aangenomen: "Jeanita",
		ingepakt: "Brenda",
	},
];

export const products = [
	{
		id: "1",
		naam: "Kabeljauw",
		prijs: 2399,
		afkomst: "Noordzee",
		vangmethode: "Wildvang",
		beschrijving: "dit is een korte beschrijving als plaatsvulling",
		bereiding: ["wokken", "bakken", "bbq"],
		levertijd: "op voorraad",
	},
	{
		id: "2",
		naam: "Zalm",
		prijs: 2399,
		afkomst: "Noordzee",
		vangmethode: "Wildvang",
		beschrijving: "dit is een korte beschrijving als plaatsvulling",
		bereiding: ["wokken", "bakken", "bbq"],
		levertijd: "op voorraad",
	},
	{
		id: "3",
		naam: "Tong",
		prijs: 2399,
		afkomst: "Noordzee",
		vangmethode: "Wildvang",
		beschrijving: "dit is een korte beschrijving als plaatsvulling",
		bereiding: ["wokken", "bakken", "bbq"],
		levertijd: "op voorraad",
	},
	{
		id: "4",
		naam: "Heek",
		prijs: 2399,
		afkomst: "Noordzee",
		vangmethode: "Wildvang",
		beschrijving: "dit is een korte beschrijving als plaatsvulling",
		bereiding: ["wokken", "bakken", "bbq"],
		levertijd: "op voorraad",
	},
	{
		id: "5",
		naam: "Zeebaars",
		prijs: 2399,
		afkomst: "Noordzee",
		vangmethode: "Wildvang",
		beschrijving: "dit is een korte beschrijving als plaatsvulling",
		bereiding: ["wokken", "bakken", "bbq"],
		levertijd: "op voorraad",
	},
];
